[workspace]
members = [
    "alacritty",
    "alacritty_terminal",
]

[profile.release]
lto = true
debug = 1
incremental = false

[patch.crates-io.winit]
git = "https://github.com/rust-windowing/winit"
rev = "84f26b0e5ecb2b1254206af7e3a0d485c5f78836"
